[package]
name = "abc163"
version = "0.1.0"
authors = ["originbenntou <originbenntou8973@gmail.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]
once_cell = "1.7.2"

[profile.release]
lto = true
panic = 'abort'
